codium --install-extension christian-kohler.npm-intellisense
codium --install-extension CoenraadS.bracket-pair-colorizer-2
codium --install-extension DavidAnson.vscode-markdownlint
codium --install-extension dbaeumer.vscode-eslint
codium --install-extension donjayamanne.githistory
codium --install-extension eg2.vscode-npm-script
codium --install-extension JuanBlanco.solidity
codium --install-extension mikestead.dotenv
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-mssql.mssql
codium --install-extension ms-python.python
codium --install-extension PKief.material-icon-theme
codium --install-extension redhat.java
codium --install-extension redhat.vscode-xml
codium --install-extension tomoki1207.pdf
codium --install-extension VisualStudioExptTeam.vscodeintellicode
codium --install-extension vscjava.vscode-java-debug
codium --install-extension vscjava.vscode-java-dependency
codium --install-extension vscjava.vscode-java-pack
codium --install-extension vscjava.vscode-java-test
codium --install-extension vscjava.vscode-maven
codium --install-extension vscode-icons-team.vscode-icons
codium --install-extension zhuangtongfa.material-theme
